# Site settings
title: Dominik Knafelj
subtitle: Software Developer
email: d.knafelj@gmail.com
description: My personal blog
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Dominik Knafelj
street_address: 
city: Fort Lauderdale
state: FL
zip_code: 55555
country: United States of America
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
  github_url: https://github.com/dominikknafelj
gitlab_url: https://gitlab.com/u/dknafelj
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/knafelwebsolutions/<Paste> 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Jamsven

# Build settings
markdown: kramdown

sass:
  style: compressed
